name: Api JsonPlaceholder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Configure Python
      uses: actions/setup-python@v5
    
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
    
    - name: Run Tests
      run: |
        robot -d ./results tests

    - name: Send Report
      if: always()
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        report_path: ./results
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        show_passed_tests: true

    - name: Rename report File to index for gh-pages
      run: |
        mv ./results/report.html ./results/index.html

    - name: Publish report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./results
    